# version: '3'
# services:
#   sqlite3:
#     container_name: sqlite3_container
#     image: nouchka/sqlite3:latest
#     stdin_open: true
#     tty: true
#     volumes:
#       #Modify following line
#       - "/tmp/servers.json:/servers.json"
#     ports:
#       - '80:8080' # expose ports - HOST:CONTAINER
#     restart: unless-stopped

version: "3.8"
services:
  db:
    image: postgres
    container_name: local_pgdb
    restart: always
    ports:
      - "54320:5432"
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: admin
    volumes:
      - local_pgdata:/var/lib/postgresql/data
  pgadmin:
    image: dpage/pgadmin4
    container_name: pgadmin4_container
    restart: always
    ports:
      - "5050:80"
    environment:
      PGADMIN_DEFAULT_EMAIL: raj@nola.com
      PGADMIN_DEFAULT_PASSWORD: admin
    volumes:
      - pgadmin-data:/var/lib/pgadmin

volumes:
  local_pgdata:
  pgadmin-data: